# Development
# baseURL = "http://localhost:1313"
# Production
baseURL = "https://aldair.com.mx/portfolio"
title = "Writing Portfolio - Aldair"
theme = "hugo-geekdoc"

pluralizeListTitles = false

# Using the Geekdoc theme with two modifications:
# /layouts/partials/site-header.html
# Change the base URL to the blog's main address.
# /layouts/partials/site-footer.html
# Change the default footer for the Creative commons footer.

# Geekdoc required configuration
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true

# Required if you want to render robots.txt template
enableRobotsTXT = true

# Needed for mermaid shortcodes
[markup]
  [markup.goldmark.renderer]
    # Needed for mermaid shortcode
    unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 9

[taxonomies]
  tag = "tags"

[security.exec]
    allow = ['^asciidoctor$']
