---
title: "Caddy"
date: 2023-09-17
draft: false
---

[IMPORTANT]
====
Solus is not a server operating system. Usage of server packages outside local testing is not recommended.
====

Caddy is installed with a default configuration that you can customize as needed.

== Installation

To install `caddy`, use the Software Center or execute the following command:

[source,bash]
----
sudo eopkg install caddy
----

== Configuration

You can configure Caddy using a _Caddyfile_, a text file that contains configuration directives. The default Caddyfile is located at `/usr/share/caddy/Caddyfile`. 

To reload Caddy with a new configuration file, use the following command:

[source,bash]
----
caddy reload --config /path/to/new/caddyfile
----

For more information, see the Caddy documentation at link:https://caddyserver.com/docs/[https://caddyserver.com/docs/].

== Management

You can use the following commands to manage Caddy:

* Enable Caddy on startup and start immediately after enabling: `sudo systemctl enable --now caddy`
* Stop Caddy: `sudo systemctl stop caddy`